
"use client"
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { useRouter } from 'next/navigation'
import { usePathname } from 'next/navigation'



import NavBar from '@/app/comp/NavBar'
import Footer from "@/app/comp/Footer"

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  // const router = useRouter();
  const pathname  = usePathname()

  const isHomeOrProfilePage = pathname  === '/' || pathname  === '/profile'

  return (
    <html lang="en">
      <body className={inter.className}>

        {isHomeOrProfilePage && <NavBar />
        }
        {children}

        {isHomeOrProfilePage && <Footer />}
      </body>
    </html>
  )
}
