





import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'



import NavBar from '@/app/comp/NavBar'
import Footer from "@/app/comp/Footer"


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {



  return (
    <html lang="en">
      <body className={inter.className}>

      
        {children}

       
      </body>
    </html>
  )
}


// "use client"

// import './globals.css'
// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
// import { usePathname } from 'next/navigation'



// import NavBar from '@/app/comp/NavBar'
// import Footer from "@/app/comp/Footer"


// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {

//   // const router = useRouter();
//   const pathname  = usePathname()

//   const isHomeOrProfilePage = pathname  === '/' || pathname  === '/profile'

//   return (
//     <html lang="en">
//       <body className={inter.className}>
//       {/* <body > */}

//         {isHomeOrProfilePage && <NavBar />
//         }
//         {children}

//         {isHomeOrProfilePage && <Footer />}
//       </body>
//     </html>
//   )
// }


// RootLayout.js



// "use client"
// import './globals.css'
// import { useEffect } from 'react';
// // import { useRouter } from 'next/router';
// import { usePathname } from 'next/navigation'

// import { Inter } from 'next/font/google';
// import type { Metadata } from 'next';

// import NavBar from '@/app/comp/NavBar';
// import Footer from '@/app/comp/Footer';

// const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// const RootLayout = ({ children }: { children: React.ReactNode }) => {
//   const pathname  = usePathname()

//   useEffect(() => {
//     // Check if the current page is not the login or signup page
//     const isHomeOrProfilePage = !(pathname === '/login' || pathname === '/signup');

//     // Conditionally render NavBar and Footer based on the current page
//     if (isHomeOrProfilePage) {
//       // Render NavBar only on the home and profile pages
//       // You can add additional conditions if needed
//       console.log('Render NavBar');
//     }

//     // Clean up if needed
//     return () => {
//       // Any cleanup logic goes here
//     };
//   }, [pathname]);

//   return (
//     <html lang="en">
//       <body className={inter.className}>
//       {pathname === '/' && <NavBar />}

//         {children}
//         {pathname === '/profile' && <Footer />}
//       </body>
//     </html>
//   );
// };

// export default RootLayout;
